version: "3"
services:
  app-server:
    image: spring-boot-docker
    ports:
      - 8080:8085
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=kucinghitam
      - DATABASE_PASSWORD=blackcat
      - DATABASE_NAME=test_db
      - DATABASE_PORT=3306
    networks:
      - backend

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=kucinghitam
      - MYSQL_PASSWORD=blackcat
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend

networks:
  backend:

